<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Tu Carrito</h1>
    <?php
    foreach ($productsCart as $product) {
        echo $product->getIdProduct(). " x" . $product->getQuantity();
    }
    ?>
    <form action="index.php?c=cart&finish=1" method="POST">
        <input type="submit" name="finishBuys" value="Finalizar Compra">
    </form>
    <a href="index.php">Seguir Comprando</a>
</body>

</html>