<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Tu Carrito</h1>
    <?php
    $total = 0;
    foreach ($productsCart as $product) {
        foreach ($products as $prod) {
            if ($prod->getId() == $product->getIdProduct()) {
                $totalProducto = $prod->getPrice() * $product->getQuantity();
                $total += $totalProducto;
                echo $prod->getName() . " - $" . $prod->getPrice() . " | x" . $product->getQuantity() . " = $" . $totalProducto . "<br>";
            }
        }
    }
    ?>
    <hr>
    <h3>Total a pagar: $<?php echo $total; ?></h3>
    <?php
    if (!empty($productsCart)) { ?>
        <form action="index.php?c=cart&cart=<?php echo $_GET['cart'] ?>&finish=1" method="POST">
            <input type="submit" name="finishBuys" value="Finalizar Compra">
        </form>

        <form action="index.php?c=cart&cart=<?php echo $_GET['cart']; ?>" method="POST">
            <input type="submit" name="clearCart" value="Vaciar Carrito">
        </form>
    <?php
    }
    ?>
    <a href="index.php">Seguir Comprando</a>
</body>

</html>