<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Crear categoría</h2>

    <form action="index.php?c=category" method="post">
    <label>Nombre:</label><br>
    <input type="text" name="name" required><br><br>

    <label>Descripción:</label><br>
    <textarea name="description" rows="3" cols="30"></textarea><br><br>

    <input type="submit" name="createCategory" value="Crear">
    </form>

<a href="index.php">Volver</a>
</body>
</html>