<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="index.php?c=product&create=1" method="POST" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="Nombre del producto" required>
        <textarea name="description" placeholder="Descripción del producto" required></textarea>
        <input type="number" step="0.01" name="price" placeholder="Precio del producto" required>
        <input type="number" step="0" name="stock" placeholder="Stock inicial" required>
        <input type="number" step="0" name="idCategoria" placeholder="Numero de categoria" required>
        <input type="file" name="productImage" required>
        <input type="submit" name="createProductSubmit" value="Crear Producto">
    </form>
    <a href="index.php">Volver</a>
</body>

</html>