<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    if (!empty($_SESSION['user'])) {
        echo "<a href='index.php?c=user&logout=1'>Cerrar Sesión</a>";
    }
    ?>
    | <a href='index.php?c=cart&cart=<?php echo CartRepository::getCartByUserId($_SESSION["user"]->getId())->getId() ?>'>Mi Carrito</a>

    <?php
    echo " | <a href='index.php?c=user&profile=1'>Mi Perfil</a>";

    if ($_SESSION['user']->getRol()) {
        echo " | <a href='index.php?c=product&create=1'>Crear producto</a>";
    } else {
        echo "<a href='index.php?c=user&login=1'>Iniciar Sesión</a> | <a href='index.php?c=user&register=1'>Registrarse</a>";
    }
    ?>
    <?php
    foreach ($products as $product) {
        echo "<div>";
        echo "<img src='public/img/" . $product->getImage() . "' alt='" . $product->getName() . "' style='width:150px;height:150px;'>";
        echo "<h2>" . $product->getName() . "</h2>";
        echo "<p>Precio: $" . $product->getPrice() . "</p>";
        echo "<a href='index.php?c=product&id=" . $product->getId() . "'>Ver Producto</a>";
        if (!empty($_SESSION['user'])) {
    ?>
            | <a href='index.php?c=productCart&cart=<?php echo CartRepository::getCartByUserId($_SESSION["user"]->getId())->getId() ?>&add=<?php echo $product->getId() ?>'>Agregar al Carrito</a>
    <?php
        }
        if ($_SESSION['user']->getRol()) {
            echo " | <a href='index.php?c=product&delete=1&id=" . $product->getId() . "'>Eliminar producto</a>";
        }
        echo "</div>";
    }
    ?>
</body>

</html>