<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    if (!empty($_SESSION['user'])) {
        echo "<a href='index.php?c=user&logout=1'>Cerrar Sesión</a>";
    } else {
        echo "<a href='index.php?c=user&login=1'>Iniciar Sesión</a> | <a href='index.php?c=user&register=1'>Registrarse</a>";
    }
    ?>
    <?php
    foreach ($products as $product){
        echo "<div>";
        echo "<h2>" . $product->getName() . "</h2>";
        echo "<p>Precio: $" . $product->getPrice() . "</p>";
        echo "<a href='index.php?c=product&id=" . $product->getId() . "'>Ver Producto</a>";
        echo "</div>";
    }
    ?>
</body>

</html>