<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Historial de pedidos</h1>
    <?php
    if (empty($orders)) {
        echo "No hay pedidos";
    } else {
        foreach ($orders as $order) {
          echo "<div>";
          echo "<p><strong>Pedido #".$order->getId()."</strong></p>";
          echo "<p>Fecha: ".$order->getDate()."</p>";
          echo "<hr>";
          echo "</div>";
        }}
    ?>
    <a href="index.php?c=user&profile=1">Volver al perfil</a>
</body>
</html>