<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="public/style.css">
    </head>

    <body>
        <h2>Registro de usuario</h2>

        <form action="index.php?c=user" method="POST" enctype="multipart/form-data">
            <input type="text" name="username" placeholder="Nombre de usuario" required>
            <input type="password" name="password" placeholder="Contraseña" required>
            <input type="password" name="password2" placeholder="Repetir contraseña" required>
            <input type="email" name="email" placeholder="Tu E-Mail" required>
            <input type="number" name="phone" placeholder="Tu telefono" required>
            <input type="file" name="avatar">
            <input type="submit" name="registerSubmit" value="Registrar">
        </form>

        <p>¿Ya tienes una cuenta? <a href="index.php?c=user&login=1">Inicia Sesión</a></p>
        <a href="index.php">Volver</a>
    </body>

    </html>
</body>

</html>