<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>Compra realizada</h2>

    <p>¡Gracias por tu compra!</p>

    <p>Gracias por tu compra, <strong><?= $_SESSION["user"]->getUsername() ?></strong>.</p>
    <p>Total: <strong><?= number_format($total, 2) ?> €</strong></p>

    <h2>Detalles del pedido:</h2>  
        <p><strong>Fecha del pedido:</strong> <?= $order->getDate() ?></p>
        <p><strong>Estado:</strong> <?= $order->getStatus() ?></p>
        <p><strong>Total pagado:</strong> <?= number_format($total, 2) ?> €</p>
    

    <a href="index.php">Volver a la tienda</a>
</body>

</html>